Copyrights
strongloop/loopback-getting-started-intermediate pull request #44
Opened 2019-05-07 19:57 UTC by agnes512

### Description

#### Related issues

- connect to https://github.com/strongloop-internal/scrum-apex/issues/406

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

2019-05-07 20:12 UTC, dhmlau requested changes

2019-05-07 20:12 UTC, dhmlau commented on client/js/services/lb-services.js
> +
I think it's missing the text about `This file is licensed under the MIT License...`

2019-05-08 14:58 UTC, jannyHou approved these changes

2019-05-08 22:02 UTC, dhmlau approved these changes

2019-05-08 22:02 UTC, merged